name = "JSBSim"
uuid = "1735446d-a1d9-49ef-8d9f-4aa6b1e90fb9"
authors = ["Bertrand Coconnier <bcoconni@users.sourceforge.net>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
JSBSim_jll = "1f2de530-32af-5b65-a726-9f0f4dbc15ee"
