name: Build & Test
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') || github.event_name == 'pull_request' }}
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.5'
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-latest
        arch:
          - x64
    steps:
      - name: Set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Checkout JSBSim.jl
        uses: actions/checkout@v3
      - name: Checkout JSBSim
        uses: actions/checkout@v3
        with:
          repository: JSBSim-Team/jsbsim
          ref: 'v1.1.5'
          path: JSBSim
      - name: Build package
        uses: julia-actions/julia-buildpkg@latest
      - name: Test package
        uses: julia-actions/julia-runtest@latest
